homepage = "https://hugo-macinblog.pages.dev/"
languageCode = 'zh-cn'
name = "Macin"
theme = 'farallon'
features = ["minimalist"]
min_version = "0.75.0"

license = "MIT"
description = "minimalist"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[outputs]
  home = ['HTML', 'JSON', 'RSS']

[Params]
  search=true
  toc = true
  since = '2017'

[menu]
  [[menu.main]]
  name="文章"
  url="/post/"
  weight="1"  
  [[menu.main]]
  name="分类"
  url="/categories/"
  weight="2"  
  [[menu.main]]
  name="标签"
  url="/tags/"
  weight="3"  
  [[menu.main]]
  name="足迹"
  url="/about/"
  weight="4"  
  [[menu.main]]
  name="关于"
  url="/about/"
  weight="5"

[sitemap]
  changefreq = 'weekly'
  priority = 0.5
  filename = 'sitemap.xml'

[author]
  name = 'Macin CHEN'
  homepage = "https://macin.org"
